AdminBundle\Entity\Annonces:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\AnnoncesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
        images:
            type: text
        valide:
            type: boolean
        active:
            type: boolean
    lifecycleCallbacks: {  }
